PORTVERSION=	1.3.1
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP

MAINTAINER=	andoriyu@gmail.com
COMMENT=	Terminal-based Twitter Client. Realtime tweetstream, compose, search , favorite … and much more fun directly from terminal

LICENSE=	MIT

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}twitter>0:${PORTSDIR}/net/py-twitter \
							${PYTHON_PKGNAMEPREFIX}
