# $FreeBSD$

PORTNAME=	reptyr
PORTVERSION=	0.6.3a
CATEGORIES=	sysutils

USE_GITHUB=	yes
GH_ACCOUNT=	nelhage
GH_PROJECT=	reptyr
GH_TAGNAME=	6fb15adb4552e170bcd5e648803da83dba57283b

MAINTAINER=	andoriyu@gmail.com
COMMENT=	Reparent a running program to a new terminal


USES=gmake

OPTIONS_DEFINE=	BASH
OPTIONS_SUB=	yes

.include <bsd.port.mk>
