--- Cargo.toml.orig	2021-04-10 00:10:49 UTC
+++ Cargo.toml
@@ -47,7 +47,7 @@ itertools = "0.10.0"
 log = "0.4.14"
 prettytable-rs = "^0.8"
 regex = "1"
-reqwest = { version = "0.11", features = ["blocking", "json", "native-tls-vendored"] }
+reqwest = { version = "0.11", features = ["blocking", "json", "native-tls"] }
 serde = {version = "1.0.123", features = ["derive"]}
 serde_json = "1.0"
 simple-error = "0.2.3"
